dist: focal
language: python
python:
  - "3.11"
install:
  - pip install -r requirements.txt
  - pip install coveralls black flake8
env:
  global:
    - AWS_DEFAULT_REGION="us-east-1"
    - MAIN_EB_APP_NAME="soundscape-explorer-main"
    - MAIN_EB_ENV_NAME="soundscape-explorer-main-env-1"
before_script:
  - black --check .
  - flake8 --max-line-length=88 --ignore=E501,E203
script:
  - coverage run --source='.' manage.py test
  - coverage report
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "us-east-1"
  app: $MAIN_EB_APP_NAME
  env: $MAIN_EB_ENV_NAME
  bucket_name: "elasticbeanstalk-us-east-1-783764603041"
  on:
    branch: main

after_success:
  - coveralls
