# Generated by Django 4.1.1 on 2024-10-18 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sounddata_s3", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NYCIncidentSoundData",
        ),
    ]
