branch-defaults:
  test-db-prod:                       #To be given by whoever deploys
    environment: sprint-5-test-env    #To be given by whoever deploys
    group_suffix: null
environment-defaults:
  sprint-5-test-env:                  #To be given by whoever deploys
    branch: null
    repository: null
global:
  application_name: sprint-5-test     #To be given by whoever deploys
  branch: null
  default_ec2_keyname: prod-test-db-eb-keypair
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
