# Generated by Django 4.1.1 on 2024-11-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soundscape_user", "0003_remove_soundfileuser_user_soundfileuser_user_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoundDescriptor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptor", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
