# Generated by Django 4.1.1 on 2024-10-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chatroom",
        ),
        migrations.RemoveField(
            model_name="message",
            name="explorer",
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="latitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="longitude",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chatroom",
            name="state",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name="Explorer",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
