# Generated by Django 4.1.1 on 2024-10-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatroom", "0003_alter_explorer_options_alter_explorer_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="explorer",
            name="username",
            field=models.CharField(
                default="default_username", max_length=150, unique=True
            ),
        ),
    ]
